SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS infotv_pages CASCADE;
DROP TABLE IF EXISTS infotv_themes CASCADE;
DROP TABLE IF EXISTS infotv_theme_styles CASCADE;
DROP TABLE IF EXISTS infotv_font_families CASCADE;
DROP TABLE IF EXISTS infotv_font_faces CASCADE;
DROP TABLE IF EXISTS infotv_users CASCADE;
SET FOREIGN_KEY_CHECKS=1;
