DROP TABLE IF EXISTS infotv_page CASCADE;
DROP TABLE IF EXISTS infotv_theme CASCADE;
DROP TABLE IF EXISTS infotv_theme_style CASCADE;
DROP TABLE IF EXISTS infotv_font_family CASCADE;
DROP TABLE IF EXISTS infotv_font CASCADE;
DROP TABLE IF EXISTS infotv_user CASCADE;

