DROP TABLE IF EXISTS infotv_pages CASCADE;
DROP TABLE IF EXISTS infotv_themes CASCADE;
DROP TABLE IF EXISTS infotv_theme_styles CASCADE;
DROP TABLE IF EXISTS infotv_font_familys CASCADE;
DROP TABLE IF EXISTS infotv_fonts CASCADE;
DROP TABLE IF EXISTS infotv_users CASCADE;

